# Generated by Django 4.2.7 on 2023-11-05 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('discription', models.CharField(max_length=200)),
                ('priority', models.CharField(blank=True, max_length=200)),
                ('startDate', models.CharField(max_length=50)),
                ('endDate', models.CharField(max_length=50)),
                ('plant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='finalProject_app.plants')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('workTitle', models.CharField(max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('workOrder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='finalProject_app.workorders')),
            ],
        ),
    ]
