# Generated by Django 4.2.7 on 2023-11-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject_app', '0002_workorders_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorders',
            old_name='discription',
            new_name='description',
        ),
    ]
