# Generated by Django 4.2.7 on 2023-11-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject_app', '0003_rename_discription_workorders_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorders',
            name='endDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='startDate',
            field=models.DateField(blank=True),
        ),
    ]
