# Generated by Django 4.2.7 on 2023-11-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalProject_app', '0004_alter_workorders_enddate_alter_workorders_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorders',
            name='endDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workorders',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
